### ISSUE TITLE
Hello, I have a question.

### ISSUE THREAD

**Issue by Kimsangbeom** [quiubas/quiubas-node#2]
In the dashboard, the letters were sent out. 
but I am not receiving a success response on the Node JS code.
Only the null value is over as err.
Is there a problem?

**Comment by asfo** [comment]
Hi, thanks for reporting this issue, I'm going to test it so we can fix it if there is an error, can you tell me if this happens only in the /sms endpoint?

**Comment by asfo** [comment]
I already included a patch for fixing this, seems like it was a global issue since the response was changed to null if there is no errors instead of false.

Hope this fixes any error and you can use this library as intended :)

Thanks for your report 👍
